author: Doug
author_url: https://github.com/dougzilla32
module: CPKCoreLocation
module_version: 1.0.0
copyright: "[![badge-mit](https://img.shields.io/badge/license-MIT-blue.svg)](https://github.com/dougzilla32/CancelForPromiseKit/blob/master/LICENSE)"
readme: README.md
root_url: https://dougzilla32.github.io/CPKCoreLocation/api
dash_url: https://dougzilla32.github.io/CPKCoreLocation/api/docsets/CPKCoreLocation.xml
github_url: https://github.com/dougzilla32/CPKCoreLocation
github_file_prefix: https://github.com/dougzilla32/CPKCoreLocation/tree/master
