os: osx
language: swift
matrix:
  include:                                              
#   - {osx_image: xcode8.3, env: 'SWFT=3.1  PLAT=macOS    DST="arch=x86_64"'}
#   - {osx_image: xcode8.3, env: 'SWFT=3.1  PLAT=iOS      DST="OS=10.3.1,name=iPhone SE"'}
#   - {osx_image: xcode8.3, env: 'SWFT=3.1  PLAT=tvOS     DST="OS=10.2,name=Apple TV 1080p"'}
#   - {osx_image: xcode8.3, env: 'SWFT=3.1  PLAT=watchOS  DST="OS=3.2,name=Apple Watch - 38mm"'}

#   - {osx_image: xcode9.2, env: 'SWFT=3.2  PLAT=macOS    DST="arch=x86_64"'}
#   - {osx_image: xcode9.2, env: 'SWFT=3.2  PLAT=iOS      DST="OS=11.2,name=iPhone SE"'}
#   - {osx_image: xcode9.2, env: 'SWFT=3.2  PLAT=tvOS     DST="OS=11.2,name=Apple TV"'}
#   - {osx_image: xcode9.2, env: 'SWFT=3.2  PLAT=watchOS  DST="OS=4.2,name=Apple Watch - 38mm"'}

#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=macOS    DST="arch=x86_64"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=iOS      DST="OS=8.4,name=iPhone 4s"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=iOS      DST="OS=9.3,name=iPhone SE"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=iOS      DST="OS=10.3.1,name=iPhone SE"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=iOS      DST="OS=11.2,name=iPhone SE"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=tvOS     DST="OS=10.2,name=Apple TV 1080p"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=tvOS     DST="OS=11.2,name=Apple TV"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=watchOS  DST="OS=3.2,name=Apple Watch - 38mm"'}
#   - {osx_image: xcode9.2, env: 'SWFT=4.0  PLAT=watchOS  DST="OS=4.2,name=Apple Watch - 38mm"'}

    - {osx_image: xcode9.3, env: 'SWFT=4.1  PLAT=macOS    DST="arch=x86_64"'}
cache:
  directories:
  - Carthage
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLAT --verbose
install:
  - xcodebuild -scheme CPKCoreLocation -quiet -destination "$DST" SWIFT_VERSION=$SWFT SWIFT_TREAT_WARNINGS_AS_ERRORS=YES build-for-testing -enableCodeCoverage YES
script:
  - if [ "$PLAT" != "watchOS" ]; then
      xcodebuild -scheme CPKCoreLocation -quiet -destination "$DST" SWIFT_VERSION=$SWFT SWIFT_TREAT_WARNINGS_AS_ERRORS=YES test -enableCodeCoverage YES;
    fi
